Repository WSUCEG-7140/Tempus_Fugit_Minecraft, pull requests merged in 2023-07, with the labels that each got.

#55 Speed down with test
  README.md
  pyproject.toml
  tempus_fugit_minecraft/main.py
  tests/test_main.py
Labels: enhancement

#60 Pass-through-clouds issue #57
  tempus_fugit_minecraft/main.py
  tests/test_main.py
Labels: enhancement, testing

#63 Split files out
  tempus_fugit_minecraft/main.py
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/utilities.py
  tempus_fugit_minecraft/window.py
  tests/test_cloud.py
  tests/test_main.py
  tests/test_pause_menu.py
  tests/test_speed.py
Labels: documentation, enhancement

#65 Speed down with test
  README.md
  tempus_fugit_minecraft/window.py
  tests/test_speed.py
Labels: enhancement, testing

#69 Split Player Logic From Window
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/window.py
  tests/test_cloud.py
  tests/test_player.py
  tests/test_speed.py
Labels: enhancement

#73 No blocks adjacent to cloud issue#42
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/window.py
  tests/test_cloud.py
Labels: documentation, enhancement, testing

#75 added new sound class to play sounds. Also sound when removing a block
  assets/sound/rock_hit.wav
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/sound.py
  tempus_fugit_minecraft/sound_list.py
  tests/test_sound.py
Labels: enhancement

#76 Move game logic from window to model
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/utilities.py
  tempus_fugit_minecraft/window.py
  tests/test_cloud.py
  tests/test_model.py
  tests/test_player.py
  tests/test_speed.py
Labels: enhancement

#77 No cross boundaries issue#25
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/utilities.py
  tests/test_player.py
Labels: documentation, enhancement, testing

#81 Add trees issue#80
  README.md
  assets/texture.png
  tempus_fugit_minecraft/block.py
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/player.py
  tests/test_block.py
  tests/test_model.py
  tests/test_player.py
Labels: documentation, enhancement, testing

#83 Add ascend and descend while flying
  README.md
  tempus_fugit_minecraft/block.py
  tempus_fugit_minecraft/main.py
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/shaders.py
  tempus_fugit_minecraft/sound.py
  tempus_fugit_minecraft/utilities.py
  tempus_fugit_minecraft/window.py
  tests/test_block.py
  tests/test_flying.py
  tests/test_lighting.py
  tests/test_model.py
  tests/test_pause_menu.py
  tests/test_player.py
  tests/test_sound.py
  tests/test_speed.py
Labels: enhancement

#87 Enhance game issue#44 issue#84
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/utilities.py
  tests/test_model.py
  tests/test_player.py
Labels: documentation, enhancement, testing

#88 Night lighting
  tempus_fugit_minecraft/shaders.py
  tempus_fugit_minecraft/window.py
  tests/test_lighting.py
Labels: enhancement

#91 Bakursait doxygen
  tempus_fugit_minecraft/block.py
  tempus_fugit_minecraft/main.py
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/shaders.py
  tempus_fugit_minecraft/sound.py
  tempus_fugit_minecraft/sound_list.py
  tempus_fugit_minecraft/utilities.py
  tempus_fugit_minecraft/window.py
  tests/test_model.py
Labels: documentation

#96 Final Documentation Improvements
  tempus_fugit_minecraft/block.py
  tempus_fugit_minecraft/main.py
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/shaders.py
  tempus_fugit_minecraft/sound.py
  tempus_fugit_minecraft/sound_list.py
  tempus_fugit_minecraft/utilities.py
  tempus_fugit_minecraft/window.py
Labels: documentation

#90 Higher jump
  README.md
  tempus_fugit_minecraft/block.py
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/window.py
  tests/test_block.py
  tests/test_jump.py
  tests/test_model.py
  tests/test_player.py
  tests/test_speed.py
Labels: documentation, enhancement, testing

#94 Mark embedded doc
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/shaders.py
  tempus_fugit_minecraft/sound.py
  tempus_fugit_minecraft/sound_list.py
  tempus_fugit_minecraft/window.py
Labels: documentation

#93 World
  .github/workflows/python-app.yml
  tempus_fugit_minecraft/model.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/utilities.py
  tempus_fugit_minecraft/world.py
  tests/test_model.py
  tests/test_player.py
  tests/test_world.py
Labels: documentation, testing

#107 Player create dark clouds
  README.md
  pyproject.toml
  tempus_fugit_minecraft/block.py
  tempus_fugit_minecraft/player.py
  tests/test_block.py
  tests/test_player.py
Labels: enhancement

#102 Added sprinting and slow walk
  poetry.lock
  pyproject.toml
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/window.py
  tests/test_player.py
  tests/test_window.py
Labels: enhancement

#116 Programming by contract examples
  README.md
  tempus_fugit_minecraft/player.py
  tests/test_window.py
Labels: testing

#106 Specifying units 103
  tempus_fugit_minecraft/block.py
  tempus_fugit_minecraft/game_model.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/window.py
  tempus_fugit_minecraft/world.py
  tests/test_block.py
  tests/test_flying.py
  tests/test_game_model.py
  tests/test_jump.py
  tests/test_model.py
  tests/test_player.py
  tests/test_speed.py
  tests/test_window.py
  tests/test_world.py
Labels: documentation

#111 Added meeting minutes
  Meeting_Minutes.txt
Labels: documentation

#101 Sound volume adjustment
  assets/volume_knob.png
  assets/volume_slider.png
  tempus_fugit_minecraft/game_model.py
  tempus_fugit_minecraft/shaders.py
  tempus_fugit_minecraft/sound_list.py
  tempus_fugit_minecraft/window.py
  tests/test_sound.py
  tests/test_window.py
Labels: enhancement

#117 Bakursait lp renaming variables
  README.md
  tempus_fugit_minecraft/block.py
  tempus_fugit_minecraft/player.py
  tempus_fugit_minecraft/world.py
  tests/test_world.py
Labels: enhancement
